In [ ]:
##python
#Python was created by Guido Van Rossum and released in 1991
# powerful computer language
# simple and easy to learn
#free and opensource
#interactive
##portable
#object oriented
#interpreted -- bytecode -- translated to native lang -- bytecode -- portable
## Dynamic
## python is a cross platform programming language
## Mac os, Linux,port to java , dotnet
## modular programmin - python support of modules and package facilities
## Modular programming and reuse of code
##python uses whitespace and indentation to delimit blocks
##its high level language
##rich set of libraries

In [ ]:
# Python used for many purposes
# 
#Web development - server side web development
#software development - python can help with s/w testing, bug tracking and build control
#Data science - Python is used for data analysis, data visualization, and other datascience tasks
#Machine learning - python is used in machine learning
#Desktop applications: python can be used to build desktop applications including
#manay linux and open source applications


In [ ]:
# single line comment(#)
'''
Comments are hints that we add to our code to make it easier to understand.
Python comments start with #(single line comment)
We should use comments:
For future references, as comments make our code readable.
For debugging.
For code collaboration, as comments help peer developers to understand each other's code.
Note: Comments are not and should not be used as a substitute to explain poorly written code. 
Always try to write clean, understandable code, and then use comments as an addition.
In most cases, always use comments to explain 'why' rather than 'how' and you are good to go.
Note: This approach comes in handy while working with large files. 
Instead of deleting any line, we can use comments and identify which one is causing an error.
'''

In [ ]:
## variables , identifiers

In [1]:
import sys

In [2]:
print(sys.version)

3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]


In [3]:
import platform

In [4]:
platform.python_version()

'3.9.12'

In [175]:
print(dir(__builtins__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError

In [9]:
help("modules")


Please wait a moment while I gather a list of all available modules...



D:\AnacondaS\lib\site-packages\navigator_updater\utils\py3compat.py:77: DeprecationWarning:

Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

D:\AnacondaS\lib\site-packages\nltk\twitter\__init__.py:20: UserWarning:

The twython library has not been installed. Some functionality from the twitter package will not be available.

D:\AnacondaS\lib\site-packages\notebook\utils.py:280: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\site-packages\notebook\utils.py:280: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\random.py:123: DeprecationWarning:

Seeding based on hashing is deprecated
since Python 3.9 and will be removed in a subsequent version. The only 
supported seed types are: None, int, float, str, bytes, and bytearray.

D:\AnacondaS\lib\site-packages\_distutil

D:\AnacondaS\lib\site-packages\skimage\viewer\qt.py:5: MatplotlibDeprecationWarning:


The QT_RC_MAJOR_VERSION attribute was deprecated in Matplotlib 3.5 and will be removed two minor releases later.

D:\AnacondaS\lib\site-packages\daal4py\sklearn\_utils.py:59: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\site-packages\daal4py\sklearn\_utils.py:59: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\site-packages\daal4py\sklearn\_utils.py:59: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\site-packages\daal4py\sklearn\_utils.py:59: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\site-packages\daal4py\sklearn\_utils.py:59: DeprecationWarning:

distutils Version classes are deprecated. Use packaging.version instead.

D:\AnacondaS\lib\si

Cython              commctrl            mmap                socks
Day2_practice       compileall          mmapfile            sockshandler
Day6_practice       comtypes            mmsystem            sortedcollections
Day7_practicePython concurrent          mock                sortedcontainers
IPython             conda               modulefinder        soupsieve
OpenSSL             conda_build         mpmath              spacy
PIL                 conda_content_trust msgpack             spacy_legacy
Practice Python     conda_env           msilib              spacy_loggers
PyQt5               conda_pack          msvcrt              sphinx
Python_Practice     conda_package_handling multidict           spyder
TBB                 conda_token         multipledispatch    spyder_kernels
__future__          conda_verify        multiprocessing     sqlalchemy
_abc                confection          munkres             sqlite3
_aix_support        configparser        murmurhash          sre_compile


In [ ]:
# #### Identifiers : Names given objects or variables or functions or classes 
# ## rules for identifiers :
# * Start with either a letter ( A - Z a -z) or an underscore (_)
# * can be followed by any combination of letters (A-Z a -z) digits (0-9) and underscore 
# * NO punctuation or special character allowed
# * Case Sensitive
# * No reserved words can be used as identifiers : class if else return def for in 
# * NO predefined/ builtins should be used as identifiers : print len int str 

In [10]:
# ### Python DataTypes 
# 1. Numerical
#     * int 
#     * float
#     * complex
#     * bool
# 2. Character/string : stringtype 

In [11]:
print(dir())

['In', 'Out', '_', '_4', '_8', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'platform', 'quit', 'sys']


In [12]:
a = 32
b = 24.0
c = 12 + 4j
d = True
e = False

In [13]:
a = 32; b=24.0;c=12+4j ; d=True;e=False

In [17]:
type(a)

int

In [16]:
type(b)


float

In [18]:
type(c)

complex

In [19]:
a,b,c,d,e = 32,24.56,15_4j,True,False

In [28]:
print(a,type(a),b,type(b),type(c),type(d),type(e), sep ='\n')

32
<class 'int'>
24.56
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bool'>


In [20]:
s = "hello world"

In [21]:
s

'hello world'

In [ ]:
# ### Operators in Python :
# * Assignment operator : = 
# * Arithmetic Operators : + - / *  ** (exponent) % (modulus) // (integer divide) 
# * Arithmetic combined with assignment operators : a = a+b can be written as a += b . : += -= 
# * Realtional Operators : == , != , > < >= <=
# * Logical operators and - &, or - | , not , in, not in


In [36]:
num1=2
num2=3
sum1=num1+num2
prod1= num1*num2
div1 = num1/num2
div2 = num1//num2
mod1= num1 % num2
prd2 = num1 ** num2
print(sum1)
print(prod1)
print(div1)
print(mod1)
print(prd2)

5
6
0.6666666666666666
2
8


In [37]:
a = 10
b =20

In [38]:
a == 10

True

In [39]:
a > 10

False

In [40]:
a != b

True

In [54]:
#membership operators
##in and not in

##in operators returns true if a variable is found in specified sequence and false otherwise

a is not b

True

In [41]:
a == b

False

In [42]:
##imput operation

name = input("enter your name")
print(name)

enter your namelakshmi padmasree
lakshmi padmasree


In [ ]:
#enter sub1 marks,sub2 marks and the print the output

In [57]:
sub1 = int(input(sub1))
sub2 = int(input(sub2))
totalmarks = sub1 + sub2
print(totalmarks)

9090
8080
170


In [46]:
str1 = "python"
str2 = "  programming"


In [51]:
str1 +=str2

In [52]:
print(str1)

python  programming  programming


In [56]:
basic_pay = float(input('Enter basic salary : '))
HRA = 0.1 * basic_pay
TA = 0.05 * basic_pay
salary = basic_pay + HRA + TA
print('Total Salary : %f' % salary)

Enter basic salary : 34567
Total Salary : 39752.050000


In [58]:

##Conditional branching statements
##python supports different types of conditional branching statements
#if statement
#if-else statement
#nested if statement
#if-elif-else statment

## if statement is the simpliest form of decision control statements
#that is frequenty used in decision making


In [61]:

## check the given number is even or odd number
num = int(input("please enter a number"))

please enter a number11


In [62]:
## given number is even or odd
if (num%2 == 0):
    print("Even")
else:
    print("Odd")

Odd


In [63]:
## write a program to find the greatest of two numbers


a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b"))
if (a > b):
    greatest = a
else:
    greatest = b
print("greatest ", greatest)


Enter the value of a:30
Enter the value of b40
greatest  40


In [67]:
## write a program to find the greatest of three numbers


a = int(input("Enter the value of a"))
b = int(input("Enter the value of b"))
c = int(input("Enter the value of c"))
if (a > b) and (a>c):
    greatest = a
elif (b >= a) and (b >= c):
     greatest = b
else:
      greatest = c   
print("greatest ", greatest)

Enter the value of a2
Enter the value of b3
Enter the value of c4
greatest  4


In [71]:

#Enter any number as input and show the number divisible by 5
num = int(input("Enter the number"))
if(num % 5 == 0) :
    print ("Divisible by 5")
else:
    print ("Not divisible by 5")


Enter the number23
Not divisible by 5


In [74]:
# how much you need to add or subtract to make the number divisible by 5

num = int(input("Enter a number: "))
remainder = num%5
if remainder <= 2:
    print(f"-{remainder}")
else:
    print(5-remainder)

Enter a number: 43
2


In [76]:
#number divisible by 5
num = int(input ("Enter a number : "))
rem = num%5
if(rem == 0):
    print("The number is divisible by 5")
else:
    print(rem, 
          " shoud be subtracted or %d much be added to %d to make it completely divisible by 5 " %(10-rem,num))

Enter a number : 23
3  shoud be subtracted or 7 much be added to 23 to make it completely divisible by 5 


In [79]:

# take input marks and grade them :
# A => 90 and above
# B => 75 - 90
# C => 55 - 75
# D => 35 - 55
# F => <35

marks = int(input("Enter the marks: ")) 

if  (marks >= 90):
            grade = 'A'
elif(75 <= marks < 90):
           grade = 'B'
elif (55 <= marks < 75):
        grade = 'C'
elif (35 <= marks < 55):
            grade = 'D'
else:
            grade = 'F'

print(f"Marks: {marks}, Grade: {grade}")

Enter the marks: 30
Marks: 30, Grade: F


In [82]:
## accept a  number and print whether it is  two digit number or three
##digit number else print it more than three digits

num = int(input("enter a number"))
if 9 < num < 99:
    print("this is two digit number")
elif 99 < num < 999:
    print("Three digit nuber")
elif 999 < num < 9999:
    print ("Four digit number")
else:
    print("number is <=9 or >=9999")



enter a number12345
number is <=9 or >=9999


In [ ]:
##Write a program to determine the character entered is a vowel or not




In [ ]:
## iterative control structures
##for loop
##while loop
#python supports basic loop structures.
#Iterative statements are used to repeat the execution of one or more statements
#In python, iterative statements are implemented through 
#while loop and for loop and nested loops


## for loop when i know the number of iterations 
#( ex is want print first 5 number)

## while loop --  condition - when the condition is met exit from loop

#statement x
'''
while (condition) :
    statement block
statement y
'''



In [83]:

## To print first 10 number using while loop
i = 0
while(i<=10):
    print(i, end = ' ')
    i = i+2
    

0 2 4 6 8 10 

In [84]:
## write a program to calculate the sum and avg of first 10 numbers


sum =0
for i in range(11):
    sum+=i
print('sum of first 10 numbers', sum)
average = sum /10;
print ("Average of first 10 numbers", average)

sum of first 10 numbers 55
Average of first 10 numbers 5.5


In [85]:
i = 0
s = 0
while(i<=10):
    print(i)
    s = s + i
    i = i + 1

avg = s/10

print("The sum of first 10 digits :" ,s)
print("The average of first 10 numbers is :" ,avg)


0
1
2
3
4
5
6
7
8
9
10
The sum of first 10 digits : 55
The average of first 10 numbers is : 5.5


In [86]:
i = 0
total = 0
while (i <=10):
    total += i
    print(i, end=" ")
    i+= 2
print(f"\nTotal: {total}")
print(f"Average: {total/10}")

0 2 4 6 8 10 
Total: 30
Average: 3.0


In [ ]:
#Flow control statements : used with a combination of loop and condition
#break : terminates the loop
#continue : skips the remaining steps for that iteration

In [87]:
i = 0
while (i < 10):
    i = i + 1
    if(i == 5):
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [90]:
while True:
    str = input ("Enter a string (bye to exit) : ")
    if str == "bye":
        break
    print(str)
else:
    print("Exiting......")

Enter a string (bye to exit) : 

Enter a string (bye to exit) : 

Enter a string (bye to exit) : bye


In [91]:

##For loop
#The range() function

#The range() is built in function in python that is used to 
#iterate over a sequence of numbers. The syntax of range()
#is range(begin,end,[step])
#The range generates a sequence of numbers starting with begin(inclusive) and ending with one less than the end
#The step argument is optional, by default every number in the range is increased by 1, but we can specify a different increment using step
#it can be both negative and positive but not zero

In [92]:
for i in range(1,6):
    print(i,end=' ')

1 2 3 4 5 

In [98]:
for i in range(0,10,2):
    print(i,end=' ')

0 2 4 6 8 

In [99]:
for i in "PYTHON":
    print(i,end=' ')

P Y T H O N 

In [102]:
for i in range(1,20):
    if i%5 == 0:
        continue
    else:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


In [ ]:
## Datastructures
## Tuple()
## List []
## set {}
##Dictionary{key : value}


In [103]:
#A tuple is one dimensional ,
#immutable ordered sequence of items which can have mixed datatypes

tup1 = (12,'lakshmi',45.3,(3,2),True)


In [104]:
tup1

(12, 'lakshmi', 45.3, (3, 2), True)

In [105]:
##access the dataset at index value 2
tup1[2]

45.3

In [106]:
tup1[1]

'lakshmi'

In [107]:
##accessing elements with positive index
##tup1[1] = 'Padmasree'

##A tuple is immutable and cannot be modified

TypeError: 'tuple' object does not support item assignment

In [108]:
tup1[-1]

True

In [109]:
##accesing with negative index
tup1[-3]

45.3

In [110]:
## count starts from first index and stops before the second index
tup1[1:4]

('lakshmi', 45.3, (3, 2))

In [ ]:
## List -- one dimensional mutable ordered sequence of items 
#which can be of mixed datatypes

In [112]:
list1=['lakshmi',101,25.6,True,11]   ##created a list

In [113]:
list1    ##view the list

['lakshmi', 101, 25.6, True, 11]

In [114]:
list1.append('abc') ##add new items

In [115]:
list1

['lakshmi', 101, 25.6, True, 11, 'abc']

In [116]:
list1.remove(101)  ## remove the items

In [117]:
list1

['lakshmi', 25.6, True, 11, 'abc']

In [119]:
list1.append(101)

In [123]:
list1.insert(3,4)    ## modify list to insert a new item at a certain index

In [127]:
list1.insert(6,100)

In [128]:
list1

['lakshmi', 25.6, 4, 11, 'abc', 101, 100]

In [126]:
list1.pop(2)   ##accessing the elements by index position

True

In [129]:
list1[5]

101

In [130]:
## slice the list
list1[1:4]

## count starts from first index and stops before the second index

[25.6, 4, 11]

In [ ]:
##Dictionaries store a mapping between a set of keys and a set of values
# ## Dictionaries : key value pairs of data 
#     d = {key : value }

# ##### Key : can any python object but need to be immutable and unique for that dictionary (Num, string, tup)
##### Value : can be any arbitrary Python object ( number string list tup ...)
## define,modify,view,lookup


In [131]:
d = {'name' : 'lakshmi'}

In [132]:
emp = {'name' : 'lakshmi','exp' : 10,'desg':'Trainer'}

In [133]:
emp

{'name': 'lakshmi', 'exp': 10, 'desg': 'Trainer'}

In [134]:
emp.keys()

dict_keys(['name', 'exp', 'desg'])

In [135]:
emp.values()

dict_values(['lakshmi', 10, 'Trainer'])

In [136]:
input1 = {'Brazil' :['Brasilia', 'Russia':'Moscow','India': 'Delhi', 'China':'Beijing','South Africa':'Pretoria'}

In [137]:
input1

{'Brazil': 'Brasilia',
 'Russia': 'Moscow',
 'India': 'Delhi',
 'China': 'Beijing',
 'South Africa': 'Pretoria'}

In [138]:
input1 = {'Brazil' :['Brasilia',17.3], 'Russia':['Moscow',3.28],'India':['Delhi',4.5], 
          'China':['Beijing',9.6],'South Africa':['Pretoria',1.22]}

In [139]:
input1

{'Brazil': ['Brasilia', 17.3],
 'Russia': ['Moscow', 3.28],
 'India': ['Delhi', 4.5],
 'China': ['Beijing', 9.6],
 'South Africa': ['Pretoria', 1.22]}

In [140]:
input1.keys()

dict_keys(['Brazil', 'Russia', 'India', 'China', 'South Africa'])

In [141]:
input1.values()

dict_values([['Brasilia', 17.3], ['Moscow', 3.28], ['Delhi', 4.5], ['Beijing', 9.6], ['Pretoria', 1.22]])

In [142]:
input1.update({'Brazil' :['Brasilia',18.3]})

In [143]:
input1

{'Brazil': ['Brasilia', 18.3],
 'Russia': ['Moscow', 3.28],
 'India': ['Delhi', 4.5],
 'China': ['Beijing', 9.6],
 'South Africa': ['Pretoria', 1.22]}

In [144]:
input1.update({'xyz':['abc',10.9]})

In [145]:
input1

{'Brazil': ['Brasilia', 18.3],
 'Russia': ['Moscow', 3.28],
 'India': ['Delhi', 4.5],
 'China': ['Beijing', 9.6],
 'South Africa': ['Pretoria', 1.22],
 'xyz': ['abc', 10.9]}

In [149]:
#set : A set is an unorderd collectionof unique elements
##create a set

set1=set(['Audi','BMW','Ferrari','GM','Mercedes'])

In [150]:
set1   ##view the set

{'Audi', 'BMW', 'Ferrari', 'GM', 'Mercedes'}

In [151]:
type(set1)   ##view the object type

set

In [153]:

set1=set(['Audi','BMW','Ferrari','GM','Mercedes'])
set2=set(['Ferrari','GM','ford','Toyota','Zen'])

In [ ]:
## set opetations -- AND (intersection operations- common in both sets),
##OR (union operations - all the elements from both the sets)

In [154]:
result = set1 | set2

In [155]:
result

{'Audi', 'BMW', 'Ferrari', 'GM', 'Mercedes', 'Toyota', 'Zen', 'ford'}

In [156]:
result = set1 & set2

In [157]:
result

{'Ferrari', 'GM'}

In [158]:
studentlist = ['abc','bcd','cde','def','efg']

In [159]:
'c' in studentlist   ## testing the presence of a string

True

In [160]:
'x' in studentlist

False

In [ ]:
## in operator is used to generate a Boolean value 
#to indicate whether a given value is present in the container or not

In [163]:
word ='abcd'

In [164]:
't' in word

False

In [165]:
'c' in word

True

In [166]:
tup1 = (68,96,71)
tup2 = (92,87,83)

In [167]:
result = tup1 + tup2

In [168]:
result

(68, 96, 71, 92, 87, 83)

In [169]:
list1 = [68,96,71]
list2 =  [92,87,83]
result = list1+list2
result

[68, 96, 71, 92, 87, 83]

In [172]:
result = list1*list2
'''
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [171], in <cell line: 1>()
----> 1 result = list1*list2

TypeError: can't multiply sequence by non-int of type 'list'
'''

TypeError: can't multiply sequence by non-int of type 'list'

In [173]:
result = list1 * 3

In [174]:
result

##repeating original content

[68, 96, 71, 68, 96, 71, 68, 96, 71]

In [176]:
###functions


'''Predefined Functions:
String Function
Number Functions
Date Functions
String functions:
String is a sequence of characters in Python. The data type of String in Python is called “str”.
How to create a String in Python :There are several ways to create strings in Python.
We can use ‘ (single quotes)
We can use ” (double quotes)
Triple double quotes “”” and triple single quotes ”’ are used for creating multi-line strings in Python.'''


'Predefined Functions:\nString Function\nNumber Functions\nDate Functions\nString functions:\nString is a sequence of characters in Python. The data type of String in Python is called “str”.\nHow to create a String in Python :There are several ways to create strings in Python.\nWe can use ‘ (single quotes)\nWe can use ” (double quotes)\nTriple double quotes “”” and triple single quotes ”’ are used for creating multi-line strings in Python.'

In [177]:
#Accessing Strings:
str = "learning Datascience"
# displaying whole
print(str)


learning Datascience


In [178]:
# displaying first character of
print(str[0])
# displaying third character 
print(str[2])
# displaying the last characterof the 
print(str[-1])
# displaying the second last 
print(str[-2])


l
a
e
c


In [179]:

'''String Operators:

Operator Description

+ It is known as concatenation operator used to join the strings given either side of the operator.
* It is known as repetition operator. It concatenates the multiple copies of the same string.
[] It is known as slice operator. It is used to access the sub-strings of a particular string.
[:] It is known as range slice operator. It is used to access the characters from the specified range.

In It is known as membership operator. It returns if a particular sub-string is present in the 
specified string.

not in It is also a membership operator and does the exact reverse of in. It returns true if a particular 
substring is not present in the specified string.

r/R It is used to specify the raw string. Raw strings are used in the cases where we need to print the 
actual meaning of escape characters such as "C://python". To define any string as a raw string, 
the character r or R is followed by the string.

% It is used to perform string formatting. It makes use of the format specifiers used in C 
programming like %d or %f to map their values in python. We will discuss how formatting is 
done in python.'''


'String Operators:\n\nOperator Description\n\n+ It is known as concatenation operator used to join the strings given either side of the operator.\n* It is known as repetition operator. It concatenates the multiple copies of the same string.\n[] It is known as slice operator. It is used to access the sub-strings of a particular string.\n[:] It is known as range slice operator. It is used to access the characters from the specified range.\n\nIn It is known as membership operator. It returns if a particular sub-string is present in the \nspecified string.\n\nnot in It is also a membership operator and does the exact reverse of in. It returns true if a particular \nsubstring is not present in the specified string.\n\nr/R It is used to specify the raw string. Raw strings are used in the cases where we need to print the \nactual meaning of escape characters such as "C://python". To define any string as a raw string, \nthe character r or R is followed by the string.\n\n% It is used to perform

In [180]:
str = "Hello" 
str1 = " world" 
print(str*3) # prints HelloHelloHello 
print(str+str1)# prints Hello world 
print(str[4]) # prints o 
print(str[2:4]); # prints ll 
print('w' in str) # prints false as w is not present in str 
print('wo' not in str1) # prints false as wo is present in str1. 
print(r'C://python') # prints C://python37 as it is written 
print("The string str : %s"%(str)) # prints The string str : Hello


HelloHelloHello
Hello world
o
ll
False
False
C://python
The string str : Hello


In [181]:
'''STRING FUNCTIONS :
Method Description
capitalize() It capitalizes the first character of the String. This function is deprecated in python3
casefold() It returns a version of s suitable for case-less comparisons.
center(width 
,fillchar)
It returns a space padded string with the original string centred with equal number 
of left and right spaces.
count(string,begin,
end)
It counts the number of occurrences of a substring in a String between begin and 
end index.
endswith(suffix 
,begin=0,end=len(s
tring))
It returns a Boolean value if the string terminates with given suffix between begin 
and end.
find(substring 
,beginIndex,
endIndex)
It returns the index value of the string where substring is found between begin 
index and end index.
format(value) It returns a formatted version of S, using the passed value.
index(subsring, 
beginIndex, 
endIndex)
It throws an exception if string is not found. It works same as find() method.
isalnum() It returns true if the characters in the string are alphanumeric i.e., alphabets or 
numbers and there is at least 1 character. Otherwise, it returns false.
isalpha() It returns true if all the characters are alphabets and there is at least one character, 
otherwise False.
isdecimal() It returns true if all the characters of the string are decimals.
isdigit() It returns true if all the characters are digits and there is at least one character, 
otherwise False.
isidentifier() It returns true if the string is the valid identifier.
islower() It returns true if the characters of a string are in lower case, otherwise false.
isnumeric() It returns true if the string contains only numeric characters.
isupper() It returns true if characters of a string are in Upper case.
isspace() It returns true if the characters of a string are white-space, otherwise false.
istitle() It returns true if the string is titled properly and false otherwise. A title string is the 
one in which the first character is upper-case whereas the other characters are 
lower-case.
join(seq) It merges the strings representation of the given sequence.
len(string) It returns the length of a string.
lower() It converts all the characters of a string to Lower case.
replace(old,new[,c
ount])
It replaces the old sequence of characters with the new sequence. The max 
characters are replaced if max is given.
split(str,num=strin
g.count(str))
Splits the string according to the delimiter str. The string splits according to the 
space if the delimiter is not provided. It returns the list of substring concatenated 
with the delimiter.
upper() It converts all the characters of a string to Upper Case.'''


# In[11]:


str="learning python"
str2="Oracle"
print(str+str2)
print(str2*5)
print(str[2:6])
print("Sigma" in str)
print("Sigma" not in str)
print(r'c://Python')
print("String format is %s"%str)
print(len(str))
print(str.capitalize())
print(str2.isupper())
print(str.istitle())
print("{} {}".format(str,str2))
l=10
b=20
print("{} {}".format(l,b))
print(str.count('l'))
print(str.find('g'))
print(str.split(" "))


learning pythonOracle
OracleOracleOracleOracleOracle
arni
False
True
c://Python
String format is learning python
15
Learning python
False
False
learning python Oracle
10 20
1
7
['learning', 'python']


In [182]:
'''
Number Functions:
These functions are of four types :
Numeric Functions
Logarithmic and Power Functions
Trigonometric and Angular Functions
Special and Constant Functions
Mathematical operations can be performed with ease by importing a module named “math”.
1. ceil() :- This function returns the greatest integral value. If number is already integer, same number is returned.
2. floor() :- This function returns the smallest integral value . If number is already integer, same number is returned
'''


'\nNumber Functions:\nThese functions are of four types :\nNumeric Functions\nLogarithmic and Power Functions\nTrigonometric and Angular Functions\nSpecial and Constant Functions\nMathematical operations can be performed with ease by importing a module named “math”.\n1. ceil() :- This function returns the greatest integral value. If number is already integer, same number is returned.\n2. floor() :- This function returns the smallest integral value . If number is already integer, same number is returned\n'

In [183]:
import math

In [185]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [186]:
help(math.factorial)

Help on built-in function factorial in module math:

factorial(x, /)
    Find x!.
    
    Raise a ValueError if x is negative or non-integral.



In [187]:
math.factorial(5)

120

In [188]:
5*4*3*2*1

120

In [189]:

'''
Number Functions:
These functions are of four types :
Numeric Functions
Logarithmic and Power Functions
Trigonometric and Angular Functions
Special and Constant Functions
Mathematical operations can be performed with ease by importing a module named “math”.
1. ceil() :- This function returns the greatest integral value. If number is already integer, same number is returned.
2. floor() :- This function returns the smallest integral value . If number is already integer, same number is returned
'''

'\nNumber Functions:\nThese functions are of four types :\nNumeric Functions\nLogarithmic and Power Functions\nTrigonometric and Angular Functions\nSpecial and Constant Functions\nMathematical operations can be performed with ease by importing a module named “math”.\n1. ceil() :- This function returns the greatest integral value. If number is already integer, same number is returned.\n2. floor() :- This function returns the smallest integral value . If number is already integer, same number is returned\n'

In [190]:
'''Logarithmic and Power Functions
1. exp(a) :- This function returns the value of e raised to the power a (e**a) .
2. log(a, b) :- This function returns the logarithmic value of a with base b. If base is not mentioned, the computed value 
is of natural log.
'''

'Logarithmic and Power Functions\n1. exp(a) :- This function returns the value of e raised to the power a (e**a) .\n2. log(a, b) :- This function returns the logarithmic value of a with base b. If base is not mentioned, the computed value \nis of natural log.\n'

In [191]:
import math 
 
# returning the exp of 4 
print ("The e**4 value is : ", end="") 
print (math.exp(4)) 
 
# returning the log of 2,3 
print ("The value of log 2 with base 3 is : ", end="") 
print (math.log(2,3))


The e**4 value is : 54.598150033144236
The value of log 2 with base 3 is : 0.6309297535714574


In [192]:
import math 
 
# returning the value of 3**2 
print ("The value of 3 to the power 2 is : ", end="") 
print (math.pow(5,2)) 
 
# returning the square root of 25 
print ("The value of square root of 25 : ", end="") 
print (math.sqrt(9))


The value of 3 to the power 2 is : 25.0
The value of square root of 25 : 3.0


In [193]:
'''
Date Functions
1. calendar(year, w, l, c) :- This function displays the year, width of characters, no. of lines per week and column 
separations.
2. firstweekday() :- This function returns the first week day number. By default 0 (Monday).
3. isleap (year) :- This function checks if year mentioned in argument is leap or not.
4. leapdays (year1, year2) :- This function returns the number of leap days between the specified years in 
arguments.
5. month (year, month, w, l) :- This function prints the month of a specific year mentioned in arguments. It takes 4
arguments, year, month, width of characters and no. of lines taken by a week.
'''


'\nDate Functions\n1. calendar(year, w, l, c) :- This function displays the year, width of characters, no. of lines per week and column \nseparations.\n2. firstweekday() :- This function returns the first week day number. By default 0 (Monday).\n3. isleap (year) :- This function checks if year mentioned in argument is leap or not.\n4. leapdays (year1, year2) :- This function returns the number of leap days between the specified years in \narguments.\n5. month (year, month, w, l) :- This function prints the month of a specific year mentioned in arguments. It takes 4\narguments, year, month, width of characters and no. of lines taken by a week.\n'

In [194]:
import calendar

In [195]:
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [196]:
# using calender to print calendar of year 
# prints calendar of 2012 
print ("The calender of year 2012 is : ") 
print (calendar.calendar(2012,2,1,6)) 
 
#using firstweekday() to print starting day number 
print ("The starting day number in calendar is : ",end="") 
print (calendar.firstweekday()) 
if (calendar.isleap(2008)): 
 print ("The year is leap") 
else : print ("The year is not leap") 
 
#using leapdays() to print leap days between years
print ("The leap days between 1950 and 2000 are : ",end="") 
print (calendar.leapdays(1950, 2000)) 
print ("The month 5th of 2016 is :") 
print (calendar.month(2016,5,2,1)) 


The calender of year 2012 is : 
                                  2012

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5                1  2  3  4
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       5  6  7  8  9 10 11
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      12 13 14 15 16 17 18
16 17 18 19 20 21 22      20 21 22 23 24 25 26      19 20 21 22 23 24 25
23 24 25 26 27 28 29      27 28 29                  26 27 28 29 30 31
30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1          1  2  3  4  5  6                   1  2  3
 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17
16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 

In [ ]:
'''
UserDefined Functions
Function's declaration begins with the keyword def and followed by the function name.
The function may take arguments(s) as input within the opening and closing parentheses.
After defining the function name and arguments(s) a block of program statement(s) start at the next line and 
these statement(s) must be indented.

Syntax of a user defined function:
def function_name(argument1, argument2, ...) :
 statement_1
 statement_2
 ....
'''
'''
Types of Arguments in Python:
Required Arguments
Default Arguments
Keyword Arguments
Variable Arguments
Position only Argument
Required Argument:
The number of arguments is passed is as per the function declaration. 
'''



In [199]:
##required arguments x
def square(x):
    return (x*x)

In [200]:
square(3)

9

In [201]:
##default argument for y is 2 
def square1(x,y=2):
    return(x*x+2*x*y+y*y)


In [202]:
square1(5)

49

In [203]:
square1(2,3)

25

In [206]:
def add(*number):
    n=0
    for x in number:
        x+=n
    return x

In [207]:
add(10,20)

20

In [208]:
add(10,20,30,40)

40

In [209]:
add(10,20,30,40,50)

50

In [210]:
'''Lambda Functions
Lambda usage used for short hand expression building in application. 
The power of lambda is better shown when you 
use them as an anonymous function inside another function.
Small anonymous (unnamed) functions can be created with lambda keyword. 
Lambda forms can be used as an 
argument to other function where function objects are required but 
syntactically they are restricted to a single 
expression.
'''


'Lambda Functions\nLambda usage used for short hand expression building in application. \nThe power of lambda is better shown when you \nuse them as an anonymous function inside another function.\nSmall anonymous (unnamed) functions can be created with lambda keyword. \nLambda forms can be used as an \nargument to other function where function objects are required but \nsyntactically they are restricted to a single \nexpression.\n'

In [211]:
##Without Lambda :
def average(x, y):
    return (x + y)/2
print(average(4, 3))


3.5


In [212]:
#With Lambda :
print((lambda x, y: (x + y)/2)(4, 3))

3.5


In [ ]:
'''Lambda Functions:
Lambda functions have their own local namespace and cannot access variables other than those in their parameter list 
and those in the global namespace. Lambda forms can take any number of arguments but return just one value in the 
form of an expression. They cannot contain commands or multiple expressions.
We can call the following methods for lambda operators
map()
reduce()
filter()
Lambda: map() can be applied to more than one list. The lists have to have the same length. map() will apply its lambda 
function to the elements of the argument lists. Syntax: map(func, var) function applies the function func to each of the 
elements in var and returns a new list.
'''


In [215]:
list1=[20,50,39,102,339,220]
result = list(filter(lambda x:(x%5 == 0),list1))

In [216]:
result

[20, 50, 220]

In [225]:
## double each member in the list
list2=[20,50,39,102,339,220]
mylist=map(lambda x: x*2 , list2)
list(mylist)


[40, 100, 78, 204, 678, 440]

In [235]:
from functools import reduce
## product of all numbers in the list
list3=[1,2,3,4,5]


In [236]:
mylist=reduce(lambda x,y: x*y , list3)


In [237]:
mylist

120

In [ ]:
##exercise
#write a function that accepts 3 integers and return true if any of the intergers is 0.otherwise return false
#write a function that displays "Hello name" for any given name passed to it


In [238]:
def func1(a,b,c):
    return not all((a,b,c))


In [239]:

def func2(name):
    print(f"Hello {name}")

In [240]:
func1(1,0,0)

True

In [241]:
func2('lakshmi')

Hello lakshmi


In [242]:
def greet(name):
  print(f"Hello {name}")
greet("brydon")

Hello brydon


In [243]:
def check_zero(a: int, b: int, c: int):
    if a == 0 or b == 0 or c == 0:
        return True
    else:
        return False

check_zero(1,2,3)
check_zero(1,0,1)

True

In [244]:
def greet(name: str):
    print(f"Hello {name}")
greet('john')

Hello john


In [246]:
def funA(a,b,c):
    return (a == 0 or b == 0 or c == 0)

def funB(name):
    print("Hello " + name)

print(funA(0,1,2))
funB("John")

True
Hello John


In [249]:
## Numpy

distance = [10,15,17,26]
time = [.3,.47,.55,1.2]

speed = distance/time

## you cannot apply mathematical operations over the entire list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [254]:
import numpy as np
distance = [10,15,17,26]
time = [.3,.47,.55,1.2]
np_distance =np.array(distance)
np_time =np.array(time)

In [255]:
speed = np_distance/np_time

In [256]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [257]:
distance * 3

[10, 15, 17, 26, 10, 15, 17, 26, 10, 15, 17, 26]

In [258]:
np_distance*3

array([30, 45, 51, 78])

In [ ]:
'''
#NumPyis the foundational package for mathematical computing in Python.
#It has the following properties:
#Executes element-wise computations and mathematical calculations
#Tools for reading/writing array based datasets to disk
#Tools for integrating language codes (C, C++)
#Supports fast and efficient multidimensional arrays (ndarray)
#Performs linear algebraic operations, Fourier transforms, and random number generation
#Efficient way of storing and manipulating data


An Array in NumPy has the following properties(ndarray)

collection of values
add,remove,change
single type(homogeneous)
multidimensional
mathematical function support
fast and efficient


purpose of ndarray: in python ndarray is used as the primary container
to exchange data between algorithms

These arrays can be on dimensional,two dimensional,three dimensional, multi dimensional

'''

In [259]:

first_trial_cyclist=[10,15,17,26]
second_trail_cyclist =[12,11,21,24]

In [260]:

np_first=np.array(first_trial_cyclist)
np_second=np.array(second_trail_cyclist)
np_total=np_first+np_second


In [261]:
np_total

array([22, 26, 38, 50])

In [263]:
first_trial_cyclist[0]

10

In [265]:
first_trial_cyclist[0:3]

[10, 15, 17]

In [266]:
np_new = np.array([np_first,np_second])

In [267]:
np_new

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [272]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [273]:
x + y

array([[ 6,  8],
       [10, 12]])

In [274]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [275]:
np.subtract(y,x)

array([[4, 4],
       [4, 4]])

In [277]:
x.sum()

10

In [278]:
y.sum()

26

In [279]:
x.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [280]:
x.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [281]:
x.min(),x.max(),x.mean()

(1, 4, 2.5)

In [282]:
x.shape

(2, 2)

In [283]:
x.size

4

In [284]:
x[1:3]

array([[3, 4]])

In [ ]:
## universal Function(ufunc)

In [289]:
from numpy import ufunc

In [291]:

np.sqrt([2,4,9])

array([1.41421356, 2.        , 3.        ])

In [ ]:
## shape of an array using shape manipulation functions
##flatten,split,stack,reshape,resize

In [298]:
result = np.array([[10,15,17,26,23,20],[12,11,21,24,34,23]])

In [299]:
result

array([[10, 15, 17, 26, 23, 20],
       [12, 11, 21, 24, 34, 23]])

In [300]:
result.shape

(2, 6)

In [295]:
result.flatten()

array([10, 15, 17, 26, 12, 11, 21, 24])

In [301]:
result.ravel()

array([10, 15, 17, 26, 23, 20, 12, 11, 21, 24, 34, 23])

In [302]:
result.reshape(3,4)

array([[10, 15, 17, 26],
       [23, 20, 12, 11],
       [21, 24, 34, 23]])

In [303]:
result.ndim

2

In [304]:
np.hsplit(result,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 23, 20],
        [24, 34, 23]])]

In [ ]:
###The various features of Pandas makes it an efficient library for Data Scientists.
#Fast and efficient data wrangling
#Powerful data structure
#High performance merging and joining of data sets
#Tools for reading/ writing data
#Intelligent and automated data alignment
#Easy data aggregation and transformation

In [308]:
import pandas as pd
sample_data = pd.read_csv('d:/Sample_data.csv')

In [309]:
sample_data

ID  Gender  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST
0     70       0     4    1       1     1    57     52     41     47   57
1    121       1     4    2       1     3    68     59     53     63   61
2     86       0     4    3       1     1    44     33     54     58   31
3    141       0     4    3       1     3    63     44     47     53   56
4    172       0     4    2       1     2    47     52     57     53   61
..   ...     ...   ...  ...     ...   ...   ...    ...    ...    ...  ...
195   31       1     2    2       2     1    55     59     52     42   56
196  145       1     4    2       1     3    42     46     38     36   46
197  187       1     4    2       2     1    57     41     57     55   52
198  118       1     4    2       1     1    55     62     58     58   61
199  137       1     4    3       1     2    63     65     65     53   61

[200 rows x 11 columns]

In [310]:
sample_data.loc[ :,['Read', 'SST']]

Read  SST
0      57   57
1      68   61
2      44   31
3      63   56
4      47   61
..    ...  ...
195    55   56
196    42   46
197    57   52
198    55   61
199    63   61

[200 rows x 2 columns]

In [311]:
sample_data.head()

ID  Gender  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST
0   70       0     4    1       1     1    57     52     41     47   57
1  121       1     4    2       1     3    68     59     53     63   61
2   86       0     4    3       1     1    44     33     54     58   31
3  141       0     4    3       1     3    63     44     47     53   56
4  172       0     4    2       1     2    47     52     57     53   61

In [312]:


sample_data.count()

ID        200
Gender    200
Race      200
SEB       200
School    200
Prog      200
Read      200
Write     200
Math1     200
Math2     200
SST       200
dtype: int64

In [313]:
sample_data.isna()

ID  Gender   Race    SEB  School   Prog   Read  Write  Math1  Math2  \
0    False   False  False  False   False  False  False  False  False  False   
1    False   False  False  False   False  False  False  False  False  False   
2    False   False  False  False   False  False  False  False  False  False   
3    False   False  False  False   False  False  False  False  False  False   
4    False   False  False  False   False  False  False  False  False  False   
..     ...     ...    ...    ...     ...    ...    ...    ...    ...    ...   
195  False   False  False  False   False  False  False  False  False  False   
196  False   False  False  False   False  False  False  False  False  False   
197  False   False  False  False   False  False  False  False  False  False   
198  False   False  False  False   False  False  False  False  False  False   
199  False   False  False  False   False  False  False  False  False  False   

       SST  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
195  False  
196  False  
197  False  
198  False  
199  False  

[200 rows x 11 columns]

In [314]:

sample_data['Total']= sample_data.loc[ : , 'Read' :'SST'].sum(axis = 1)


In [315]:
sample_data.insert(1, 'Name', 'B', allow_duplicates=True)

